# Ultimate Volcano Global Setups
debug: true

autoStart:
  statusCheckInterval: 144000
  probability:
    dormant:
      increase: 0.05
      decrease: 0.005
    minor_activity:
      increase: 0.1
      decrease: 0.05
    major_activity:
      increase: 0.2
      decrease: 0.1
  disallowLavaPourNonVent: true

blueMap:
  enable: true

worldGuard:
  enable: true
  # If true, volcano actions will respect WorldGuard region protection
  respectRegions: true
  # Permission to bypass WorldGuard protection for volcano actions
  bypassPermission: "typhon.worldguard.bypass"

web:
  connect:
    listen:
      enable: false
      host: 0.0.0.0   # defaults to 0.0.0.0
      port: 18080     #
      #publicUrl: https://typhon-api.my-server.com   # <- use this if your public point is different (i.e. CF ArgoTunnel)
    webrtc:
      enable: true
      stunServer: stun.l.google.com:19302

  ui:
    serveBundled: false                        # whether bundled ui should be served from api server from path /web

  api: # Authentication - else the people with permission should
    auth:
      #tokens:
      #   - AuthorizedToken
      #   - username: username
      #     password: password
      issueTempToken: true      # when person runs /typhon web allow providing temporary token for that session
